name: Deploy

on:
    workflow_call:
        secrets:
            deploy_script:
                required: true

jobs:
    deploy_app:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
            - uses: actions/download-artifact@v5
              with:
                  name: lime3_app_build
                  path: builds/app/
            - uses: actions/download-artifact@v5
              with:
                  name: lime3_cli_build
                  path: builds/
            - name: Run deploy script
              run: ${{ secrets.deploy_script }}
